# Generated by Django 4.1.2 on 2022-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc_symptom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etc_Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('etc_symptom', models.TextField()),
                ('age', models.TextField(max_length=3)),
            ],
            options={
                'db_table': 'etc_symptom_post',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
